[build]
builder = "nixpacks"
buildCommand = "composer install && npm install && npm run build"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php -S 0.0.0.0:$PORT -t public"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["php81", "php81Extensions.pgsql", "nodejs", "npm"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install",
    "php artisan storage:link",
    "php artisan migrate --force",
    "php artisan cache:table",
    "php artisan session:table",
    "php artisan queue:table",
]
